//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Lysakovskiy_A_SEntities : DbContext
    {
        public Lysakovskiy_A_SEntities()
            : base("name=Lysakovskiy_A_SEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cleaning_Schedule> Cleaning_Schedule { get; set; }
        public virtual DbSet<Guest_Services> Guest_Services { get; set; }
        public virtual DbSet<Guests> Guests { get; set; }
        public virtual DbSet<Integrations> Integrations { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Room_Access> Room_Access { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<Statistics_Hotel> Statistics_Hotel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
