//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics_Hotel
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> occupancy_rate { get; set; }
        public Nullable<decimal> adr { get; set; }
        public Nullable<decimal> revpar { get; set; }
        public Nullable<decimal> revenue { get; set; }
    }
}
