//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Cleaning_Schedule = new HashSet<Cleaning_Schedule>();
        }
    
        public int id { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string user_name { get; set; }
        public string role { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public int failed_login_attempts { get; set; }
        public bool is_locked { get; set; }
        public bool is_first_login { get; set; }
        public Nullable<System.DateTime> last_login_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cleaning_Schedule> Cleaning_Schedule { get; set; }
    }
}
